-- local actions = require("telescope.actions")
--
-- require("telescope").setup({
--     defaults = {
--         layout_config = { vertical = { width = 0.9, height = 0.9 } },
--         file_ignore_patterns = { ".git" },
--         hidden = true,
--         vimgrep_arguments = { 'rg', '--color=never', '--no-heading', '--with-filename', '--line-number', '--column', '--smart-case', '--follow' },
--     },
--     pickers = {
--         find_files = {
--             find_command = { 'fd', '--type', 'f', '--follow', '--hidden', '--exclude', '.git' }
--         },
--         lsp_references = {
--             -- by default, telescope lets you type to filter the list of results further.
--             -- however, for the list of references, I only ever want to scroll up and down with j and k
--             -- here, we force it to start in normal mode
--             initial_mode = "normal",
--         },
--     },
--     extensions = {
--         emoji = {
--             action = function(emoji)
--                 -- argument emoji is a table.
--                 -- {name="", value="", cagegory="", description=""}
--                 -- insert emoji when picked
--                 vim.api.nvim_put({ emoji.value }, 'c', false, true)
--             end,
--         },
--     },
-- })
--
-- -- Enable telescope fzf native, if installed
-- pcall(require("telescope").load_extension, "fzf")
-- pcall(require("telescope").load_extension, "emoji")
--
--
-- require("toggleterm").setup({
--     size = function(term)
--         if term.direction == "horizontal" then
--             local window_height = vim.api.nvim_win_get_height(0) * 2
--             return window_height
--         elseif term.direction == "vertical" then
--             local window_width = vim.api.nvim_win_get_width(0) * 1
--             return window_width
--         end
--     end,
--     open_mapping = [[<c-\>]],
--     shell = 'fish',
--     hide_numbers = true, -- hide the number column in toggleterm buffers
--     shade_filetypes = {},
--     shade_terminals = false,
--     shading_factor = 2,     -- the degree by which to darken to terminal colour, default: 1 for dark backgrounds, 3 for light
--     start_in_insert = true,
--     insert_mappings = true, -- whether or not the open mapping applies in insert mode
--     persist_size = true,
--     direction = 'float',    -- 'vertical', 'horizontal', 'tab', or 'float'
--     close_on_exit = true    -- close the terminal window when the process exits
-- })
--
--
--
-- require('bioinformatics')
