#!/usr/bin/env bash

echo "Ran stats script at $(date)" >> /tmp/stats.log
#export DISPLAY=:0
cd $HOME/stats || exit
notify-send "start stats"
nohup $HOME/.local/statsenv/bin/jupyter lab > /dev/null 2>&1 &
