-- vim.keymap.set('n', '<leader>g', ':Telescope live_grep<cr>', { desc = "Live grep search", silent = true })
-- vim.keymap.set('n', '<leader>ff', ":Telescope find_files<cr>", { desc = "Find files", silent = true })
-- vim.keymap.set('n', '<leader>fk', ':Telescope keymaps<cr>', { desc = "Find keymaps", silent = true })
-- vim.keymap.set('n', '<leader>fe', ':Telescope emoji<cr>', { desc = "Find emoji", silent = true })
